import { TokenGetter, authorizedFetch, ensureOk } from "./http";

const API_ASSISTANT_URL = import.meta.env.VITE_API_URL + "/assistant";

/** One line of the conversation, as the panel shows it. */
export interface AssistantMessage {
  /** "user" is Kari; "assistant" is the helper. */
  role: "user" | "assistant";
  text: string;
}

/** A conversation, as the API returns it. */
export interface AssistantSession {
  id: string;
  messages: AssistantMessage[];
  /** How many more times she can write before this conversation is full. */
  turnsRemaining: number;
}

/** Whether the helper can run at all, and what it can do. */
export interface AssistantStatus {
  available: boolean;
  /** Whether it can write things down as GitHub issues. Not yet. */
  canFile: boolean;
}

/**
 * What she is looking at, sent with each message so the helper's guidance
 * matches her screen. Every field is optional: the route is always known,
 * the rest only on pages that publish them.
 */
export interface AssistantContext {
  route?: string;
  /** The kind of thing open, in her words: "haiku", "photograph". */
  what?: string;
  id?: string;
  title?: string;
  dirty?: boolean;
}

/**
 * The admin helper's API.
 *
 * Pure TypeScript on purpose — it lives in the shared package, which both
 * apps import, so it must pull in no UI at all (`test/config/
 * app-boundaries.test.ts` enforces that). The widget that renders this is
 * admin-only and lives in `apps/admin`.
 *
 * Every call needs the admin token: these routes are behind the same JWT as
 * the rest of the API.
 */
export class AssistantService {
  /**
   * Ask whether the helper is configured. The one call that succeeds even
   * when it is not — it is how the panel knows to show the resting state
   * rather than an error.
   */
  static async getStatus(
    getAccessTokenSilently: TokenGetter,
  ): Promise<AssistantStatus> {
    const response = await authorizedFetch(
      `${API_ASSISTANT_URL}/status`,
      getAccessTokenSilently,
    );
    ensureOk(response, "Failed to reach the helper");
    return await response.json();
  }

  /** Start a new conversation. The id is generated by the server. */
  static async createSession(
    getAccessTokenSilently: TokenGetter,
  ): Promise<AssistantSession> {
    const response = await authorizedFetch(
      `${API_ASSISTANT_URL}/sessions`,
      getAccessTokenSilently,
      { method: "POST" },
    );
    ensureOk(response, "Failed to start a conversation");
    return await response.json();
  }

  /**
   * Fetch a conversation by id — what the panel calls after a reload, with
   * the id it kept in local storage. Throws an `HttpError` with status 404
   * when that conversation no longer exists, which callers treat as "start
   * a fresh one" rather than as a failure.
   */
  static async getSession(
    id: string,
    getAccessTokenSilently: TokenGetter,
  ): Promise<AssistantSession> {
    const response = await authorizedFetch(
      `${API_ASSISTANT_URL}/sessions/${encodeURIComponent(id)}`,
      getAccessTokenSilently,
    );
    ensureOk(response, "Failed to load the conversation");
    return await response.json();
  }

  /**
   * Send one message and get the whole updated conversation back.
   *
   * Returning the full transcript rather than just the new lines keeps the
   * panel a mirror of the server: there is no client-side merge to get
   * wrong, and a reload shows exactly what a send showed.
   */
  static async sendMessage(
    id: string,
    text: string,
    context: AssistantContext,
    getAccessTokenSilently: TokenGetter,
  ): Promise<AssistantSession> {
    const response = await authorizedFetch(
      `${API_ASSISTANT_URL}/sessions/${encodeURIComponent(id)}/messages`,
      getAccessTokenSilently,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ text, context }),
      },
    );
    ensureOk(response, "Failed to send the message");
    return await response.json();
  }
}
