import { describe, expect, it } from "vitest";
import { RULES, declaration, label } from "./css-rules";

// The blog editor is a WYSIWYG surface: what `.tiptap` draws is a preview of
// the post, and the public site renders that same HTML back out through
// `.other-works-item-content` with no stylesheet of its own for it — the
// headings, markers and block spacing a reader sees come from the browser's
// default sheet.
//
// The admin no longer has that default sheet. #592 turns Tailwind's
// preflight on, unscoped, and preflight states exactly the properties the
// UA sheet used to give these elements: `h1..h6 { font-size: inherit;
// font-weight: inherit }`, `ol, ul, menu { list-style: none }` with the
// indent gone, and `margin: 0` across every block. Measured against the
// built stylesheets, an h1, a bulleted list and two paragraphs in the
// editor all came out 16px/400, marker-less and touching, while the
// published post showed 32px bold, disc markers and 1em between blocks.
//
// So the editor has to state them itself, and this is the test that says
// so: for every block the toolbar can produce, the properties preflight
// flattens are declared again under `.tiptap`. Without it the text-style
// dropdown and the two list buttons are controls that visibly do nothing —
// the post changes, the preview does not.
//
// Asserted on what the stylesheets DECLARE, like the other tests in this
// directory: preflight is generated by Tailwind at build time and is not in
// the sources this reader sees, so there is nothing here to diff against.
//
// Each assertion is about a property being STATED, not about its value —
// except the two list markers, where the value is the whole point. The
// heading sizes are deliberately the admin type scale's steps rather than
// the reader's exact pixels (see the comment in tiptap.css), so pinning
// them here would pin the wrong thing.

/** Every unconditional rule whose selector targets something in `.tiptap`. */
const editorRules = RULES.filter(
  (rule) =>
    rule.atRules.length === 0 &&
    rule.selector.split(",").some((part) => part.trim().startsWith(".tiptap ")),
);

/** The value `element` is given for `property` inside the editor, if any. */
function editorDeclaration(
  element: string,
  property: string,
): string | undefined {
  for (const rule of editorRules) {
    const targetsElement = rule.selector
      .split(",")
      .some((part) => part.trim() === `.tiptap ${element}`);
    if (!targetsElement) continue;
    const value = declaration(rule.block, property);
    if (value) return value;
  }
  return undefined;
}

/** Where the rules for `element` live, for a failure message worth reading. */
const rulesFor = (element: string) =>
  editorRules
    .filter((rule) =>
      rule.selector.split(",").some((part) => part.trim() === `.tiptap ${element}`),
    )
    .map(label)
    .join(", ") || "(no rule at all)";

describe("the editor previews what the post will look like", () => {
  // Reachable from the toolbar's text-style dropdown (tiptap.tsx offers
  // Heading 1-3). Preflight sets both properties to `inherit`, which renders
  // a heading as body text.
  it.each(["h1", "h2", "h3"])(
    "gives %s a size and a weight of its own",
    (heading) => {
      expect(
        {
          "font-size": editorDeclaration(heading, "font-size"),
          "font-weight": editorDeclaration(heading, "font-weight"),
        },
        `${heading} is flattened to body text by preflight; ${rulesFor(heading)}`,
      ).toEqual({
        "font-size": expect.any(String),
        "font-weight": expect.any(String),
      });
    },
  );

  // The two list buttons in the toolbar. Preflight's `list-style: none`
  // leaves a list looking exactly like the paragraphs above it.
  it.each([
    ["ul", "disc"],
    ["ol", "decimal"],
  ])("gives %s its markers back", (list, marker) => {
    expect(
      editorDeclaration(list, "list-style-type"),
      `a ${list} in the editor has no markers; ${rulesFor(list)}`,
    ).toBe(marker);
  });

  it.each(["ul", "ol"])("indents %s so the markers have somewhere to sit", (list) => {
    expect(
      editorDeclaration(list, "padding-inline-start") ??
        editorDeclaration(list, "padding-left"),
      `a ${list} in the editor is not indented; ${rulesFor(list)}`,
    ).toEqual(expect.any(String));
  });

  // Preflight zeroes the margin on every block element. Two paragraphs then
  // run together with nothing between them, which is the difference a
  // reader notices first.
  it.each(["h1", "h2", "h3", "p", "ul", "ol", "blockquote", "pre"])(
    "keeps space around %s",
    (block) => {
      expect(
        editorDeclaration(block, "margin") ??
          editorDeclaration(block, "margin-block"),
        `${block} has no space around it in the editor; ${rulesFor(block)}`,
      ).toEqual(expect.any(String));
    },
  );
});
