[package]
name = "kari-website-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version="0.7.7", features = ["multipart", "macros"] }
bytes = "1.12.1"
futures = "0.3.34"
tokio = { version = "1.53.1", features = ["full"] }
tokio-util = "0.7.19"
tower = {version = "0.5.3", features = ["full"] }
tower-http = { version = "0.7.0", features = ["cors", "limit", "trace"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
jsonwebtoken = "9.3.1"
serde_json = "1.0.151"
serde = { version = "1.0.229", features = ["derive"] }
hyper = "0.14.32"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
aws-config = "1.11.0"
aws-sdk-s3 = "1.143.0"
aws-smithy-types = "1.6.2"
aws-smithy-http = "0.64.0"
aws-sig-auth = "0.60.3"
async-trait = "0.1.92"
mime_guess = "2.0.5"
uuid = { version = "1.25.0", features = ["v4"] }
dotenv = "0.15"
image = { version = "0.25.10", default-features = false, features = ["jpeg", "png", "webp", "gif"] }

[dev-dependencies]
tower-test = "0.4.0"
http-body-util = "0.1.5"
jsonwebtoken = "9.3.1"
serde = { version = "1.0.229", features = ["derive"] }
aws-sdk-s3 = { version = "1.143.0", features = ["test-util"] }
aws-smithy-mocks = "0.3.0"
aws-smithy-runtime-api = "1.15.0"
